version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
