version: "3"
services:

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:80"
    networks: 
      - ora-modern

  backend:
    build:
      context: ./src/backend
      args:
        - SERVICE_NAME=management-api
        - SKIP_TESTS=true
    ports:
      - "5050:8080"
    networks: 
      - ora-modern

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - metabase:/metabase-data
      - ./src/metabase/plugins:/app/plugins
    environment:
        MB_PLUGINS_DIR: /app/plugins
    #   MB_DB_TYPE: postgres
    #   MB_DB_DBNAME: metabase
    #   MB_DB_PORT: 5432
    #   MB_DB_USER: metabase
    #   MB_DB_PASS: postgres
    #   MB_DB_HOST: postgres-db
    networks: 
        - ora-modern

volumes:
    metabase:

networks: 
    ora-modern:
        driver: bridge