openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /agency:
    get:
      summary: List all agencies
      operationId: listAgency
      tags:
        - agency
      responses:
        '200':
          description: A list of agencies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agencies"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Agency:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    Agencies:
      type: array
      items:
        $ref: "#/components/schemas/Agency"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
