package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 20, 2020 7:29:03 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.math.BigInteger;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name="CONTACTS"
)
public class Contacts implements java.io.Serializable {


     private BigInteger contactId;
     private Customers customers;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;

    public Contacts() {
    }

	
    public Contacts(BigInteger contactId, String firstName, String lastName, String email) {
        this.contactId = contactId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    public Contacts(BigInteger contactId, Customers customers, String firstName, String lastName, String email, String phone) {
       this.contactId = contactId;
       this.customers = customers;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phone = phone;
    }
   
     @Id 

    
    @Column(name="CONTACT_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getContactId() {
        return this.contactId;
    }
    
    public void setContactId(BigInteger contactId) {
        this.contactId = contactId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=255)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=255)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="EMAIL", nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PHONE", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


