package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 20, 2020 7:29:03 AM by Hibernate Tools 6.0.0.Alpha2


import io.quarkus.hibernate.orm.panache.PanacheEntityBase;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="COUNTRIES"
)
public class Countries  extends PanacheEntityBase implements java.io.Serializable {


     private String countryId;
     private Regions regions;
     private String countryName;
     private Set<Locations> locationses = new HashSet<Locations>(0);

    public Countries() {
    }

	
    public Countries(String countryId, String countryName) {
        this.countryId = countryId;
        this.countryName = countryName;
    }
    public Countries(String countryId, Regions regions, String countryName, Set<Locations> locationses) {
       this.countryId = countryId;
       this.regions = regions;
       this.countryName = countryName;
       this.locationses = locationses;
    }
   
     @Id 

    
    @Column(name="COUNTRY_ID", unique=true, nullable=false, length=2)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGION_ID")
    public Regions getRegions() {
        return this.regions;
    }
    
    public void setRegions(Regions regions) {
        this.regions = regions;
    }

    
    @Column(name="COUNTRY_NAME", nullable=false, length=40)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="countries")
    public Set<Locations> getLocationses() {
        return this.locationses;
    }
    
    public void setLocationses(Set<Locations> locationses) {
        this.locationses = locationses;
    }




}


