package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 27, 2020 8:51:28 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoriesId generated by hbm2java
 */
@Embeddable
public class InventoriesId  implements java.io.Serializable {


     private long productId;
     private long warehouseId;

    public InventoriesId() {
    }

    public InventoriesId(long productId, long warehouseId) {
       this.productId = productId;
       this.warehouseId = warehouseId;
    }
   


    @Column(name="PRODUCT_ID", nullable=false, precision=12, scale=0)
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }


    @Column(name="WAREHOUSE_ID", nullable=false, precision=12, scale=0)
    public long getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(long warehouseId) {
        this.warehouseId = warehouseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InventoriesId) ) return false;
		 InventoriesId castOther = ( InventoriesId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getWarehouseId()==castOther.getWarehouseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProductId();
         result = 37 * result + (int) this.getWarehouseId();
         return result;
   }   


}


