package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 20, 2020 7:29:03 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name="LOCATIONS"
)
public class Locations implements java.io.Serializable {


     private BigInteger locationId;
     private Countries countries;
     private String address;
     private String postalCode;
     private String city;
     private String state;
     private Set<Warehouses> warehouseses = new HashSet<Warehouses>(0);

    public Locations() {
    }

	
    public Locations(BigInteger locationId, String address) {
        this.locationId = locationId;
        this.address = address;
    }
    public Locations(BigInteger locationId, Countries countries, String address, String postalCode, String city, String state, Set<Warehouses> warehouseses) {
       this.locationId = locationId;
       this.countries = countries;
       this.address = address;
       this.postalCode = postalCode;
       this.city = city;
       this.state = state;
       this.warehouseses = warehouseses;
    }
   
     @Id 

    
    @Column(name="LOCATION_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(BigInteger locationId) {
        this.locationId = locationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COUNTRY_ID")
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }

    
    @Column(name="ADDRESS", nullable=false, length=255)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="POSTAL_CODE", length=20)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="CITY", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="locations")
    public Set<Warehouses> getWarehouseses() {
        return this.warehouseses;
    }
    
    public void setWarehouseses(Set<Warehouses> warehouseses) {
        this.warehouseses = warehouseses;
    }




}


