package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 27, 2020 8:51:28 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderItemsId generated by hbm2java
 */
@Embeddable
public class OrderItemsId  implements java.io.Serializable {


     private long orderId;
     private long itemId;

    public OrderItemsId() {
    }

    public OrderItemsId(long orderId, long itemId) {
       this.orderId = orderId;
       this.itemId = itemId;
    }
   


    @Column(name="ORDER_ID", nullable=false, precision=12, scale=0)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }


    @Column(name="ITEM_ID", nullable=false, precision=12, scale=0)
    public long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(long itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderItemsId) ) return false;
		 OrderItemsId castOther = ( OrderItemsId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOrderId();
         result = 37 * result + (int) this.getItemId();
         return result;
   }   


}


