package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 20, 2020 7:29:03 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategories generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_CATEGORIES"
)
public class ProductCategories implements java.io.Serializable {


     private BigInteger categoryId;
     private String categoryName;
     private Set<Products> productses = new HashSet<Products>(0);

    public ProductCategories() {
    }

	
    public ProductCategories(BigInteger categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public ProductCategories(BigInteger categoryId, String categoryName, Set<Products> productses) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.productses = productses;
    }
   
     @Id 

    
    @Column(name="CATEGORY_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(BigInteger categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="CATEGORY_NAME", nullable=false, length=255)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productCategories")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


