package com.nttdata.quarkus.management.api.model.database;
// Generated Oct 27, 2020 8:51:28 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Warehouses generated by hbm2java
 */
@Entity
@Table(name="WAREHOUSES"
)
public class Warehouses  implements java.io.Serializable {


     private BigInteger warehouseId;
     private Locations locations;
     private String warehouseName;
     private Set<Inventories> inventorieses = new HashSet<Inventories>(0);

    public Warehouses() {
    }

	
    public Warehouses(BigInteger warehouseId) {
        this.warehouseId = warehouseId;
    }
    public Warehouses(BigInteger warehouseId, Locations locations, String warehouseName, Set<Inventories> inventorieses) {
       this.warehouseId = warehouseId;
       this.locations = locations;
       this.warehouseName = warehouseName;
       this.inventorieses = inventorieses;
    }
   
     @Id 

    
    @Column(name="WAREHOUSE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(BigInteger warehouseId) {
        this.warehouseId = warehouseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOCATION_ID")
    public Locations getLocations() {
        return this.locations;
    }
    
    public void setLocations(Locations locations) {
        this.locations = locations;
    }

    
    @Column(name="WAREHOUSE_NAME", length=255)
    public String getWarehouseName() {
        return this.warehouseName;
    }
    
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="warehouses")
    public Set<Inventories> getInventorieses() {
        return this.inventorieses;
    }
    
    public void setInventorieses(Set<Inventories> inventorieses) {
        this.inventorieses = inventorieses;
    }




}


