package com.nttdata.quarkus.management.api.model;
// Generated Oct 20, 2020 7:29:03 AM by Hibernate Tools 6.0.0.Alpha2


import io.quarkus.hibernate.orm.panache.PanacheEntityBase;

import javax.persistence.*;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name="REGIONS"
)
public class Regions  extends PanacheEntityBase implements java.io.Serializable {


     private BigInteger regionId;
     private String regionName;
     private Set<Countries> countrieses = new HashSet<Countries>(0);

    public Regions() {
    }

	
    public Regions(BigInteger regionId, String regionName) {
        this.regionId = regionId;
        this.regionName = regionName;
    }
    public Regions(BigInteger regionId, String regionName, Set<Countries> countrieses) {
       this.regionId = regionId;
       this.regionName = regionName;
       this.countrieses = countrieses;
    }
   
     @Id 

    
    @Column(name="REGION_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(BigInteger regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="REGION_NAME", nullable=false, length=50)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="regions")
    public Set<Countries> getCountrieses() {
        return this.countrieses;
    }
    
    public void setCountrieses(Set<Countries> countrieses) {
        this.countrieses = countrieses;
    }




}


