CREATE OR REPLACE PROCEDURE GET_WAREHOUSE_STOCK 
(
  IN_PRODUCT_ID IN NUMBER 
, IN_WAREHOUSE_ID IN NUMBER 
, INVENTORY_RESULT OUT INTEGER
) AS 
BEGIN
  SELECT SUM(QUANTITY)
    INTO INVENTORY_RESULT
    FROM INVENTORIES
    WHERE product_id = IN_PRODUCT_ID
    AND warehouse_id = IN_WAREHOUSE_ID;
    
END GET_WAREHOUSE_STOCK;