openapi: "3.0.0"
info:
  version: 0.3.0
  title: justin-agency-api
  description: Justin Agency api
servers:
  - url: "http://localhost:8080"
paths:
  /agency:
    get:
      summary: List all agencies
      operationId: listAgency
      tags:
        - agency
      responses:
        '200':
          description: A list of agencies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agencies"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Agency:
      type: object
      required:
        - id
        - name
        - address
        - phoneNumber
        - email
        - contactPerson
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        contactPerson:
          type: string
    Agencies:
      type: array
      items:
        $ref: "#/components/schemas/Agency"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string