name: Install and Package Quarkus API

on:
  pull_request:
    branches: [master]

jobs:
  maven:

    name: Make sure Quarkus API installs and builds package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup Java Environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      # Run Maven Verify to generate all jacoco reports
      - name: Build with Maven
        run: |
          mvn -B verify -P all --file src/backend/quarkus-management-api/pom.xml

      # Run wmvn package - Oracle Modernization Quarkus Backend
      - name: Run wmvn package - Oracle Modernization Quarkus Backend
        run: |
          mvn -N io.quarkus:quarkus-maven-plugin
          mvnw package --file src/backend/quarkus-management-api/pom.xml
